[package]
name = "open_pql_macro"
description = "Internal crate used by open_pql"
license = "MIT"
version = "0.0.2"
edition = "2021"

[lib]
proc-macro = true
path = "fn_macro.rs"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true
