doc_comment_code_block_width = 80
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 80
normalize_doc_attributes = true
reorder_imports = true
style_edition = "2024"
unstable_features = true
