[package]
name = "open-pql"
version = "0.0.1"
edition = "2021"

[lib]
name = "open_pql"
path = "src/lib.rs"

[[bin]]
name = "open-pql-cli"
path = "src/main.rs"

[build-dependencies]
lalrpop = { version = "0.22.0", features = ["lexer"] }
bincode = "1.3.3"
itertools = "0.13.0"
rustc-hash = "2.0.0"
lazy_static = "1.5.0"
derive_more = { version = "1", features = ["full"] }

[dependencies]
fn_macro = { path = "fn_macro" }
bincode = "1.3.3"
derive_more = { version = "1", features = ["full"] }
fastrand = "2.1.1"
itertools = "0.13.0"
lalrpop-util = { version = "0.22.0", features = ["lexer"] }
lazy_static = "1.5.0"
regex = "1.11.1"
rustc-hash = "2.0.0"
serde = "1.0.214"
smallvec = "1.13.2"
tailcall = "1.0.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
quickcheck = { version = "1.0.3", features = [] }
quickcheck_macros = "1.0.0"

[features]
benchmark = []
x86 = []

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
#strip = "symbols"
#strip = "debuginfo"
debug = true

[lints.clippy]
nursery = "warn"
pedantic = "warn"
absolute_paths = { level = "warn", priority = 10 }
module_name_repetitions = { level = "allow", priority = 10 }
missing_errors_doc = { level = "allow", priority = 10 }
must_use_candidate = { level = "allow", priority = 10 }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage,coverage_nightly)',
] }

[[bench]]
name = "holdem7"
harness = false
required-features = ["benchmark"]

#[[bench]]
#name = "flop_cat"
#harness = false
#required-features = ["benchmark"]

#[[bench]]
#name = "equity"
#harness = false

[[bench]]
name = "math"
harness = false

[[bench]]
name = "inrange"
harness = false

[[bench]]
name = "outs"
harness = false
required-features = ["benchmark"]
