[workspace]
resolver = "3"
members = ["open-pql", "open-pql-macro"]

[workspace.package]
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = false

[workspace.dependencies]
derive_more = { version = "2", features = ["full"] }
fastrand = "2.3.0"
itertools = "0.14.0"
lalrpop = { version = "0.22.2", features = ["lexer"] }
lalrpop-util = { version = "0.22.2", features = ["lexer"] }
open_pql_macro = "0.0.2"
proc-macro2 = "1.0"
quickcheck = { version = "1.0.3", features = [] }
quickcheck_macros = "1.1.0"
quote = "1.0"
regex = "1.11.1"
rustc-hash = "2.1.1"
serde = "1.0.219"
smallvec = "1.15.1"
speedy = "0.8.7"
syn = { version = "2.0", features = ["full"] }
tailcall = "1.0.1"

[workspace.lints.clippy]
nursery = "warn"
pedantic = "warn"
needless_range_loop = { level = "allow", priority = 10 }
absolute_paths = { level = "warn", priority = 10 }
module_name_repetitions = { level = "allow", priority = 10 }
missing_errors_doc = { level = "allow", priority = 10 }
must_use_candidate = { level = "allow", priority = 10 }
